services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/configure.sh:/docker-entrypoint.d/99-geproxy-config.sh
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl
      - ./pxe:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   devdocs:
    #     condition: service_started
    #   pixie:
    #     condition: service_started
    #   user-data:
    #     condition: service_completed_successfully
    environment:
      - CCS_HOSTNAME=${CCS_HOSTNAME:-judge.gehack.nl}
      - CONTEST_HASH=${CONTEST_HASH:-contest_hash}
      - SSL_CERT_LOC=${SSL_CERT_LOC:-}
      - SSL_KEY_LOC=${SSL_KEY_LOC:-}
      - DOMAIN=${DOMAIN:-progcont}
    cap_add:
      - NET_ADMIN
    profiles:
      - all
      - pixie
      - devdocs
      - boot

  acng:
    image: sameersbn/apt-cacher-ng:3.3-20200524
    volumes:
      - ./acng:/var/cache/apt-cacher-ng
    restart: always
    ports:
      - "${PRIVATE_IP:-10.1.0.1}:${ACNG_PORT:-3142}:3142"
    profiles:
      - all
      - acng

  pixie:
    image: tuupke/pixie
    cap_add:
      - NET_ADMIN
    volumes:
      - ./pixie:/geproxy
    ports:
      - ${PRIVATE_IP:-10.1.0.1}:5353:5353/udp
    environment:
      - DB_DSN=/geproxy/pixie.sqlite?cache=shared&mode=rwc
      - "CUPS_ADDR=${PRIVATE_IP:-10.1.0.1}:631"
      - LISTEN_ADDR=127.0.0.1:4000
    restart: always
    profiles:
      - all
      - pixie

  devdocs:
    image: geproxy/devdocs
    build:
      dockerfile: ./Dockerfile
      context: ./devdocs
      args:
        languages: "${LANGUAGES:-'openjdk@17 c cpp python@3.10'}"
    profiles:
      - all
      - devdocs

  dnsmasq:
    image: geproxy/dnsmasq
    cap_add:
      - NET_ADMIN
    build:
      dockerfile: ./Dockerfile
      context: ./dnsmasq
    network_mode: host
    environment:
      - PRIVATE_IP=${PRIVATE_IP:-10.1.0.1}
      - PRIVATE_INTERFACE=${PRIVATE_INTERFACE:-lo}
      - SUBNET_START=${SUBNET_START:-10.1.0.100}
      - SUBNET_END=${SUBNET_END:-10.1.255.255}
      - SUBNET_NETMASK=${SUBNET_NETMASK:-255.255.0.0}
      - DOMAIN=${DOMAIN:-progcont}
      - DNS_RESOLVER=${DNS_RESOLVER:-1.1.1.1}
      - STATIC_LEASES=${STATIC_LEASES:-}
    volumes:
      - ./dnsmasq/dnsmasq.conf.template:/etc/dnsmasq.conf.template
      - ./pxe:/pxe
      - ./dnsmasq/dnsmasq.leases:/var/lib/misc/dnsmasq.leases
    profiles:
      - all
      - dnsmasq
      - boot

  user-data:
    image: alpine/curl
    volumes:
    - ./pxe:/pxe
    environment:
      - MACHINE_HOSTNAME=${MACHINE_HOSTNAME:-}
      - MACHINE_PASSWORD=${MACHINE_PASSWORD:-}
      - MACHINE_USERNAME=${MACHINE_USERNAME:-}
      - GITHUB_USERNAMES=${GITHUB_USERNAMES:-}
    command:
      - /bin/sh
      - -c
      - |
        set -o pipefail && 
        cat<<"EOT">/pxe/user-data
        #cloud-config
        autoinstall:
          version: 1
          drivers:
            install: true
          proxy: http://_gateway:3142
          kernel:
            flavor: hwe
          power_state:
            mode: reboot
            message: Install done, bye bye
          identity:
            hostname: ${MACHINE_HOSTNAME:-machine}
            password: ${MACHINE_PASSWORD:-$2a$12$6EyKyPDuHQcHIF7Abawva.pCLQhGs0r/3NybeiMVgaKTDPbm.a7b6}
            realname: ${MACHINE_USERNAME:-admin}
            username: ${MACHINE_USERNAME:-admin}
          ssh:
            allow-pw: false
            install-server: true
            authorized-keys: 
        $(echo "${GITHUB_USERNAMES:-tuupke}" | tr "," "\n" | (xargs -I{} curl -Sf https://github.com/{}.keys | sed -e 's/^/    - /'))
        EOT
    profiles:
      - all
      - boot
