---
- name: Enable internet
  gather_facts: false
  hosts: all
  become: yes
  handlers:
    - name: Apply sysctl config
      ansible.builtin.command: "sysctl -p"
    - name: Start ip-forwarding in /etc/sysctl.conf
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        state: present
        regexp: '^\s*net.ipv4.ip_forward\s*=\s*0'
        line: net.ipv4.ip_forward=1
      notify:
        - Apply sysctl config
  tasks:
    - name: Enable nat
      ansible.builtin.iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
      notify: Start ip-forwarding in /etc/sysctl.conf
